### ISSUE TITLE
MissingPluginException(No implementation found for method getContacts on channel github.com/clovisnicolas/flutter_contacts)

### ISSUE THREAD

**Issue by pteamup** [fluttercommunity/flutter_contacts#27]
MissingPluginException(No implementation found for method getContacts on channel github.com/clovisnicolas/flutter_contacts)
E/flutter (11181): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (11181): <asynchronous suspension>
E/flutter (11181): #1      ContactsService.getContacts (package:contacts_service/contacts_service.dart:12:40)
E/flutter (11181): <asynchronous suspension>
E/flutter (11181): #2      _MyAppState.initPlatformState (file:///C:/Users/india/AndroidStudioProjects/politics/lib/referscreencontactsfromphone.dart:59:42)
E/flutter (11181): <asynchronous suspension>
E/flutter (11181): #3      _MyAppState.initState (file:///C:/Users/india/AndroidStudioProjects/politics/lib/referscreencontactsfromphone.dart:53:5)
E/flutter (11181): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter (11181): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11181): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (11181): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (11181): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (11181): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11181): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (11181): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (11181): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (11181): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (11181): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11181): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (11181): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (11181): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (11181): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11181): #27     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
E/flutter (11181): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (11181): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (11181): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (11181): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
E/flutter (11181): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (11181): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (11181): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (11181): #37     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
E/flutter (11181): #38     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
E/flutter (11181): #39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
E/flutter (11181): #40     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
E/flutter (11181): #41     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
E/flutter (11181): #42

**Comment by pteamup** [comment]
The above error occured due to missing of this line in MainActivity in android
GeneratedPluginRegistrant.registerWith(this);
