### ISSUE TITLE
Cant Add Contact using API >= 26

### ISSUE THREAD

**Issue by cantacell** [fluttercommunity/flutter_contacts#59]
Using emulator (and physical device (Android 5.1) with API version <= 25 all work!
Using emulator (and physical device (Android 8.0) with API version >= 26 I receive the follow message when running ContactsService.addContact(contact) :

`E/flutter (15894): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter (15894): FormatException: Invalid envelope
E/flutter (15894): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:567:7)
E/flutter (15894): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (15894): <asynchronous suspension>
E/flutter (15894): #2      ContactsService.addContact (package:contacts_service/contacts_service.dart:24:16)
E/flutter (15894): #3      _AddContactPageState.build.<anonymous closure> (package:trovimap_contacts/contact_list_page.dart:1084:33)
E/flutter (15894): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (15894): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (15894): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (15894): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (15894): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (15894): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (15894): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (15894): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (15894): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (15894): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (15894): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (15894): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (15894): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (15894): #17     _invoke1 (dart:ui/hooks.dart:173:13)
E/flutter (15894): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:127:5)`

I tried to increment the compileSdkVersion to 28 into android/build.gradle file without success.

**Comment by cantacell** [comment]
With API > 25 it needs to invoke SimplePermissions.requestPermission(Permission.ReadContacts) and SimplePermissions.requestPermission(Permission.WriteContacts)
